### ISSUE TITLE
Server no longer runs

### ISSUE THREAD

**Issue by max-sanchez** [castellanos70/StarvationEvasion#28]
As of commit 5da51b3, I'm unable to start the server by running starvationevasion.server.Server.main(). 

Console output:
May 02, 2016 10:42:35 PM starvationevasion.server.model.db.backends.Sqlite connect
INFO: Connected to SQLite
May 02, 2016 10:42:35 PM starvationevasion.server.model.db.backends.Sqlite close
INFO: Closed DB
May 02, 2016 10:42:35 PM starvationevasion.sim.Simulator 
INFO: Loading and initializing model
**IOHelpers.readIndex(/sim/geography/PolygonBoarders.txt)
Stream closed
java.io.IOException: Stream closed
at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
at java.io.BufferedInputStream.fill(Unknown Source)
at java.io.BufferedInputStream.read(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
at starvationevasion.sim.io.GeographyXMLparser.(GeographyXMLparser.java:60)
at starvationevasion.sim.Model.(Model.java:136)
at starvationevasion.sim.Simulator.(Simulator.java:43)
at starvationevasion.server.Server.(Server.java:113)
at starvationevasion.server.Server.main(Server.java:934)**

**Comment by kf4x** [comment]
@Vorksholk see [3746a42](https://github.com/castellanos70/StarvationEvasion/commit/3746a42fa76d911018e270dd7d15f0c72724d023) Looks like @KTStephano changed the ignore and added .xml files therefore new polygons were not not added or the file names that were changed did not make it into the commit...

**Comment by kf4x** [comment]
I pushed up a change. Can you variety that it works?

**Comment by max-sanchez** [comment]
@javierchavez Works wonderfully, thank you!
